### ISSUE TITLE
~/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu

### ISSUE THREAD

**Issue by Demolei** [donglixp/lang2logic#4]
- Replacing the ClassNLLCriterion.cu with the method from README caused the failure installation of torch7 .  I guess whether the version of torch7 cannot be consistent with the lang2logic's ClassNLLCriterion.cu.

- I also install torch 7 without replacing the ClassNLLCriterion.cu. although torch7 install successfully, there are some error happened displayed below when I run the code with "./run.sh seq2seq jobqueries lstm".
`Starting training.	
/root/torch/extra/cunn/lib/THCUNN/ClassNLLCriterion.cu:52: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/root/torch/extra/cutorch/lib/THC/generic/THCStorage.c line=32 error=59 : device-side assert triggered
/root/torch/install/bin/luajit: cuda runtime error (59) : device-side assert triggered at /root/torch/extra/cutorch/lib/THC/generic/THCStorage.c:32
stack traceback:
	[C]: at 0x7f78f5466530
	[C]: in function '__index'
	/root/torch/install/share/lua/5.1/nn/ClassNLLCriterion.lua:52: in function 'forward'
	lstm/main.lua:211: in function 'opfunc'
	/root/torch/install/share/lua/5.1/optim/rmsprop.lua:35: in function 'rmsprop'
	lstm/main.lua:322: in function 'main'
	lstm/main.lua:373: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405e40
warning: '?.split' will not override existing symbol
using CUDA on GPU 0...	
/root/torch/install/bin/luajit: cannot open </mnt/disk_data_ssd/wanglei/lang2logic/seq2seq/jobqueries/dump_lstm/model.t7> in mode r  at /root/torch/pkg/torch/lib/TH/THDiskFile.c:670
stack traceback:
	[C]: at 0x7ff352a3e0e0
	[C]: in function 'DiskFile'
	/root/torch/install/share/lua/5.1/torch/File.lua:405: in function 'load'
	lstm/sample.lua:168: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00405e40
`

**Comment by donglixp** [comment]
I uploaded the torch7 (c0e51b98acbb54e6655343a57152b6e711ffdc2b) to GDrive. It can be downloaded from: https://drive.google.com/file/d/0B8yp1gOBCztycW42eDNNaExWSlU/view?usp=sharing .

Thanks!

**Comment by Demolei** [comment]
Thanks! I re-install the recommended version of torch7 but I met some new problem below.
`Prefix set to /home/wanglei/torch/install

Installing Lua version: LUAJIT21

CMake Error: The current CMakeCache.txt directory /home/wanglei/torch/build/CMakeCache.txt is different than the directory /afs/inf.ed.ac.uk/user/s14/s1478528/torch/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

CMake Error: The source "/home/wanglei/torch/CMakeLists.txt" does not match the source "/afs/inf.ed.ac.uk/user/s14/s1478528/torch/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
`

**Comment by Demolei** [comment]
li, I solved it with clean.sh. Thanks for your help!

**Comment by donglixp** [comment]
Thanks for your feedback. I will update README.md.
